import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { NavBar } from "@/components/NavBar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import NavBar from "@/components/NavBar";
import { SideBar } from "@/components/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <ThemeProvider>
            <div className="flex h-screen overflow-hidden">
              <SideBar />
              <div className="flex-1 flex flex-col overflow-y-auto">
                <NavBar />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
